export const ADD_PRODUCT = 'product/ADD_PRODUCT';
export const SAVE_PRODUCT_TO_LOCAL = 'product/SAVE_PRODUCT_TO_LOCAL';
export const ADD_PRODUCT_ERROR = 'product/ADD_PRODUCT_ERROR';
export const UPDATE_PRODUCT = 'product/UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ERROR = 'product/UPDATE_PRODUCT_ERROR';
export const REMOVE_PRODUCT = 'product/REMOVE_PRODUCT';
export const REMOVE_PRODUCT_ERROR = 'product/REMOVE_PRODUCT_ERROR';
export const REMOVE_PRODUCT_FROM_LOCAL = 'product/REMOVE_PRODUCT_FROM_LOCAL';